### PR TITLE
add Ukraine lang

### PR DESCRIPTION
**Pull request by kroschu**
I translated the coto as the Ukrainian analogue of the word object, cotonoma is the profile of the object. Use in everyday communication Japanese words are somewhat difficult for the Slavs. But the interface remains English, which still needs to be changed in the code for displaying the Ukrainian language, yet I do not know, therefore. For my research I use my own gitlab server, I can give access or put the modified files on my fork of cotoami. Gitlab server: https://git.treba.tk The running server on version v0.16.1 http://treba.tk:4000

### CODE REVIEW

**Comment by marubinotto** [comment]
Thank you for your pull request!

> But the interface remains English

As far as I found out, the lang code for Ukrainian language is `uk`, not `ua`. So you need to change the file name from `Ua.elm` to `Uk.elm` and the lang name from `ua` to `uk` in `Translate.elm`.

You can check your browser's lang code setting by opening Cotoami in your browser (for example, https://cotoa.me/) and checking the `lang` attributes of `<html>` tag in the page.

**Comment by kroschu** [comment]
In application start log heve error: Compiling of elm/src/Main.elm failed. Error: Command failed: /app/assets/node_modules/.bin/elm-make --yes --debug --output ../vendor/elm.js src/Main.elm
Maybe this is the reason why translation does not work?

Log:
Compiling 50 files (.ex)
,Generated cotoami app
,[error] backend port not found: :inotifywait
,
,[info] Running CotoamiWeb.Endpoint with Cowboy using http://0.0.0.0:4000
,[info] Running migrations on start...
,[info] Already up
,
,> cotoami@1.0.0 watch /app/assets
,> NPM_BIN=$(npm bin) brunch watch --stdin
,
,07:24:26 - info: compiling
,Elm compile: src/Main.elm, in elm, to ../vendor/elm.js
,/app/assets/node_modules/.bin/elm-make: line 5: /root/sysconfcpus/bin/sysconfcpus: No such file or directory
,07:24:31 - info: compiling.
,07:24:35 - info: compiling..
,07:24:36 - **error: Compiling of elm/src/Main.elm failed. Error: Command failed: /app/assets/node_modules/.bin/elm-make --yes --debug --output ../vendor/elm.js src/Main.elm**
,   /app/assets/node_modules/.bin/elm-make: line 5: /root/sysconfcpus/bin/sysconfcpus: No such file or directory
,Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
,events.js:163
,      throw er; // Unhandled 'error' event
,      ^
,
,Error: spawn notify-send ENOENT
,  at exports._errnoException (util.js:1050:11)
,  at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
,  at onErrorNT (internal/child_process.js:367:16)
,  at _combinedTickCallback (internal/process/next_tick.js:80:11)
,  at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by kroschu** [comment]
Perhaps on your server the translation will work then cause In the docker container.

**Comment by marubinotto** [comment]
@kroschu

> Maybe this is the reason why translation does not work?

No. The log says that an error occurred ("`sysconfcpus` is not found") before compiling elm code, so it's just a problem of your setup where the app is to be launched.

Since it seems you made some changes to the default setup, it's difficult for me to guess what exactly the problem is.

So, the first of all, could you launch the app in the default setup? There's an instruction at https://github.com/cotoami/cotoami#run-application-on-localhost

**Comment by marubinotto** [comment]
@kroschu

As I wrote in the first comment, you only need to change the file name from `Ua.elm` to `Uk.elm` (you changed only the module name) and add lang cases in Translate.elm (This seems ok). 

The display language is determined by browser's accept-language preferences, not by the server locale.

**Comment by kroschu** [comment]
Thanks for the help. I need to run a localized application in a container. With default config.exs not working. I want to suggest using your application to create knowledge bases in the company where I work, Kromberg & Schubert. September 1, preliminary presentation, the English interface then works may this is enough for now.
Will it be interesting for you to refine the application for internal use for the appropriate payment? Unless of course I can be interested in the management of the plant where I work.

**Comment by marubinotto** [comment]
@kroschu

>  With default config.exs not working.

I checked the changes you made to `config.exs`. You need the change because you launch the app in `development` mode. If you use the official docker images at https://hub.docker.com/r/cotoami/cotoami/tags/, it will be running in `production` mode and you can configure all the settings you need via environment variables.

**Comment by kroschu** [comment]
If you are interested, how much will it cost to limit access to the resource by a list of e-mail addresses, for example?

**Comment by kroschu** [comment]
> @kroschu
> 
> > With default config.exs not working.
> 
> I checked the changes you made to `config.exs`. You need the change because you launch the app in `development` mode. If you use the official docker images at https://hub.docker.com/r/cotoami/cotoami/tags/, it will be running in `production` mode and you can configure all the settings you need via environment variables.

Thanks, I'll try

**Comment by marubinotto** [comment]
@kroschu

Sorry, I can't take individual orders for now.

I'm going to launch a shared server next month and maybe you are interested in it ;-)

**Comment by marubinotto** [comment]
@kroschu Thanks for renaming Ua.elm to Uk.elm. Only the changes of  `Uk.elm` and `Translate.elm` will be ok for adding Ukraine lang. Could you exclude other changes specific to your environment?

**Comment by kroschu** [comment]
Certainly interested. The idea of ​​such an application was with me, I was very impressed when I found a ready implementation. I will be happy to share my ideas with regard to the development of your application later if you are interested in them.

**Comment by marubinotto** [comment]
@kroschu Thanks for the changes! 

I found a minor error in `Translate.elm`, I'll fix it after merging. 

I could successfully view the following result after fixing the error and set my browser's language to Ukraine lang:

ukraine

> I will be happy to share my ideas with regard to the development of your application

Thank you! I'd love to hear from you.

**Comment by kroschu** [comment]
I start the container:

docker run \
-dit --restart unless-stopped \
--name ukcotoami \
--link neo4j:neo4j \
--link postgres:postgres \
--link redis:redis \
--link maildev:meildev \
-e COTOAMI_URL_HOST=treba.tk \
-e COTOAMI_URL_PORT=4000 \
-e COTOAMI_REDIS_HOST=redis \
-e COTOAMI_REDIS_PORT=6379 \
-e COTOAMI_EMAIL_FROM=tukroschu@gmail.com \
-e COTOAMI_SMTP_SERVER=meildev \
-e COTOAMI_OWNER_EMAILS=tukroschu@gmail.com \
-e COTOAMI_SMTP_PORT=25 \
-e COTOAMI_NEO4J_HOST=neo4j \
-e COTOAMI_NEO4J_PORT=7687 \
-e COTOAMI_REPO_USER=postgres \
-e COTOAMI_REPO_DATABASE=cotoami_dev \
-e COTOAMI_REPO_PASSWORD=postgres \
-e COTOAMI_REPO_HOST=postgres \
-e COTOAMI_REPO_PORT=5432 \
-p 4001:80 \
-p 4000:4000 \
-v $(pwd)/assets/elm/src/App/I18n:/app/assets/elm/src/App/I18n \
cotoami/cotoami

I enter by the received link but in browser get error “Internal server error”

**Comment by marubinotto** [comment]
@kroschu Are there any error messages in the container logs?

**Comment by kroschu** [comment]
10:07:14.317 [info] Running CotoamiWeb.Endpoint with Cowboy using http://0.0.0.0:4000
,10:07:14.726 [info] Running migrations on start...
,10:07:14.948 [info] Already up
,10:07:51.499 request_id=2lc3jlthi7eo31kas40000bh [info] Header 'x-cotoami-client-id' does not exist
,10:07:51.511 request_id=2lc3jlthi0umbdsjvc000112 [info] Header 'x-cotoami-client-id' does not exist
,10:07:51.624 request_id=2lc3jlthi7eo31kas40000bh [info] state=set duration=285.807 status=404 params={} path=/api/public/session method=GET format=json controller=CotoamiWeb.SessionController action=index request_id=2lc3jlthi7eo31kas40000bh
,10:07:51.625 request_id=2lc3jlthi0umbdsjvc000112 [info] state=set duration=295.221 status=200 params={} path=/ method=GET format=html controller=CotoamiWeb.PageController action=index request_id=2lc3jlthi0umbdsjvc000112
,10:08:26.762 request_id=2lc3jnviqsgff8l4t400011i [info] Header 'x-cotoami-client-id' does not exist
,10:08:27.931 request_id=2lc3jnviqsgff8l4t400011i [info] state=set duration=1169.584 status=200 params={"email":"tukroschu@gmail.com"} path=/api/public/signin/request/tukroschu@gmail.com method=GET format=json controller=CotoamiWeb.SigninController action=request request_id=2lc3jnviqsgff8l4t400011i
,10:08:43.097 request_id=2lc3jotqohr5ghgs5o000132 [info] state=set duration=96.014 status=500 params={"token":"48klo6k1bokmg9g5j9f21ts3ski8bsreiah9b57hp5tqt7j3"} path=/signin/48klo6k1bokmg9g5j9f21ts3ski8bsreiah9b57hp5tqt7j3 method=GET request_id=2lc3jotqohr5ghgs5o000132
**,10:08:43.136 [error] #PID<0.476.0> running CotoamiWeb.Endpoint terminated**
,Server: treba.tk:4000 (http)
,Request: GET /signin/48klo6k1bokmg9g5j9f21ts3ski8bsreiah9b57hp5tqt7j3
,** (exit) an exception was raised:
,    ** (ArgumentError) cookie store expects conn.secret_key_base to be set
,        (plug) lib/plug/session/cookie.ex:173: Plug.Session.COOKIE.validate_secret_key_base/1
,        (plug) lib/plug/session/cookie.ex:168: Plug.Session.COOKIE.derive/3
,        (plug) lib/plug/session/cookie.ex:87: Plug.Session.COOKIE.get/3
,        (plug) lib/plug/session.ex:77: anonymous fn/5 in Plug.Session.fetch_session/1
,        (cotoami) lib/cotoami_web/router.ex:7:

**Pull request merged**
